# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot = {
    initrd.availableKernelModules = [ "nvme" "ehci_pci" "xhci_pci" "rtsx_pci_sdmmc" ];
    initrd.kernelModules = [ "dm-snapshot" ];
    kernelParams = [ "iomem=relaxed" "iwlwifi.swcrypto=0" "bluetooth.disable_ertm=1" ];
    kernelModules = [ "kvm-amd" "snd-seq" "snd-rawmidi" "nct6775" "v4l2loopback" ];
    extraModulePackages = [ ];
  };

  powerManagement.enable = true;

  boot.initrd.luks.devices.sn850-crypt = {
    device = "/dev/disk/by-uuid/f11af895-ea0b-4053-bb71-97f1896e2506";
    allowDiscards = true;
    preLVM = true;
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/2D89-4D2E";
    fsType = "vfat";
  };

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/a723b3f9-1d61-4254-815a-4ffd2285adae";
    fsType = "btrfs";
    options = [ "subvol=@nixos" "compress=zstd" ];
  };

  fileSystems."/home" =
  { device = "/dev/disk/by-uuid/a723b3f9-1d61-4254-815a-4ffd2285adae";
  fsType = "btrfs";
  options = [ "subvol=@home" "compress=zstd" ];
  };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/5460a21c-d279-41e2-990e-1e7b66c5620e"; }
    ];


  }
