# Do not modify this file!	It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.	Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, ... }:

{
	imports = [
		<nixpkgs/nixos/modules/installer/scan/not-detected.nix>
	];

	boot = {
		initrd.availableKernelModules = [
			"xhci_pci"
			"ehci_pci"
			"ahci"
			"nvme"
			"usb_storage"
			"usbhid"
			"uas"
			"sd_mod"
		];

		kernelModules = [ "kvm-amd" ];
		extraModulePackages = [ ];
	};

	fileSystems = {
		"/" = {
			device = "/dev/disk/by-uuid/edcdb9c3-c01c-4d52-be10-d19879553f91";
			fsType = "btrfs";
			noCheck = true;
		};

		"/boot" = {
			device = "/dev/disk/by-uuid/3D04-D640";
			fsType = "vfat";
		};

		"/media/storage" = {
			device = "/dev/disk/by-uuid/d54cf5fb-f74d-46f1-9a2b-001c07fdb422";
			fsType = "btrfs";
			options = [ "nofail" "noauto" "x-systemd.automount" ];
		};

		"/media/backup" = {
			device = "/dev/disk/by-uuid/aad5ac37-057e-4f18-88ff-81632eefe237";
			fsType = "btrfs";
			options = [ "nofail" "noauto" "x-systemd.automount" ];
		};

		"/media/backup2" = {
			device = "/dev/disk/by-uuid/56cd0ce4-63a1-4146-873c-b565a19f5d10";
			fsType = "btrfs";
			options = [ "nofail" "noauto" "x-systemd.automount" ];
		};

		"/home" = {
			device = "/dev/disk/by-uuid/0d52b88d-3955-42b5-b091-6f8ffc3452ae";
			fsType = "btrfs";
			noCheck = true;
			options = [ "subvol=@home" ];
		};
	};

	swapDevices = [
		{ device = "/dev/disk/by-uuid/dc871ccb-2841-4b41-95dc-184fe08e3c77"; }
	];

	nix.maxJobs = lib.mkDefault 4;
	powerManagement.cpuFreqGovernor = lib.mkDefault "performance";
}
